import fs from 'node:fs';
import crypto from 'node:crypto';
const root=new URL('../',import.meta.url).pathname;
const read=p=>fs.readFileSync(root+p,'utf8');
const must=(ok,msg)=>{if(!ok)throw new Error(msg);console.log('PASS',msg)};
const rr=read('supabase/functions/subscription-reconcile/index.ts');
const sa=read('supabase/functions/service-plans-admin/index.ts');
const act=read('supabase/functions/subscription-activate/index.ts');
const ref=read('supabase/functions/payment-refund/index.ts');
const cust=read('portal-customer.js');
const adm=read('portal-admin.js');
const live=read('GO_LIVE_RECURRING_V24_5.sql');
must(rr.includes('includeSubObjects=true'),'reconciler reads authoritative subscription + payment subobjects');
must(rr.includes('provider_subscription_payment_id'),'reconciler keys cycles by provider payment id');
must(rr.includes('provider_payment_number'),'reconciler stores provider payment number');
must(rr.includes('uniq.size === 1'),'transaction resolution refuses ambiguous matches');
must(rr.includes('isAchCleared'),'ACH is not treated as paid without clearing logic');
must(rr.includes('payment_source: "recurring"'),'recurring ledger rows are classified recurring');
must(rr.includes('invoice_source: "recurring"'),'recurring invoices are classified recurring');
must(sa.includes('case "cancel-subscription"'),'admin-only subscription cancellation action exists');
must(sa.includes('method: "DELETE"'),'cancellation stops provider subscription');
must(ref.includes('payment_source: orig.payment_source'),'refund preserves recurring workflow axis');
must(ref.includes('subscription_id: orig.payment_source === "recurring"'),'refund remains attached to subscription');
must(cust.includes("i.invoice_source === 'recurring'"),'customer one-time pay UI blocks recurring invoices');
must(adm.includes('spCancelSubscription'),'admin cancellation UI exists');
must(adm.includes('spActivateSubscription'),'admin activation UI exists');
must(act.includes('activation_date_in_past'),'activation refuses historical production start dates');
must(live.includes("service_plan_contract_mode must be live"),'go-live SQL requires live contract mode');
must(live.includes("recurring_billing_enabled','true"),'go-live gate is explicit');
console.log('All V24.5 static assertions passed.');
